spring:
  datasource:
    url: ${cdm_app_db_url:jdbc:mysql://rainbowdemo.com:33306/rbdm_syst?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${cdm_app_db_username:root}
    password: ${cdm_app_db_password:123456}
    # type=com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:com/rainbowdemo/service/basic/systemmana/mapper/mybatis/**/*.xml