spring:
  datasource:
    url: ${cdm_app_db_url:jdbc:mysql://localhost:3306/szcdm_flight?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${cdm_app_db_username:root}
    password: ${cdm_app_db_password:root}
    # type=com.alibaba.druid.pool.DruidDataSource